[package]
name = "pangenome-range-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Research CLI for pangenome-range"

[dependencies]
gbz.workspace = true
gbz-base.workspace = true
pangenome-range-build = { path = "../pangenome-range-build" }
pangenome-range-format = { path = "../pangenome-range-format" }
pangenome-range-query = { path = "../pangenome-range-query" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
simple-sds.workspace = true

[lints]
workspace = true

[[bin]]
name = "pangenome-range"
path = "src/main.rs"
